### PR TITLE
added image & json for SchoolCoin Project

### PR DESCRIPTION
**Pull request by tgroh007**

### CODE REVIEW

**Comment by jerme404** [comment]
It looks like you only checked in the dist/coins.json file, and the discord link points to canarycoin.

**Review by jerme404 — APPROVED** [review]
Awesome awesome, thanks!

**Comment by tgroh007** [comment]
schoolcoingithub

**Comment by tgroh007** [comment]
yo, i moved SchoolCoin repo to a new account, and gave myself collaborative
privileges but it saying I don't have privileges, Not sure the issues.

Thomas Groh
NGiNDesigns
509.828.9482 <javascript:void(0);>
tgroh@protonmail.com <Tgroh007@gmail.com>

**Comment by tgroh007** [comment]
nvm my bad, i did a pull request from the forkmaps master, sorry about
that!

Thomas Groh
NGiNDesigns
509.828.9482 <javascript:void(0);>
tgroh@protonmail.com <Tgroh007@gmail.com>

**Pull request merged**
