### PR TITLE
changed the size of schoolcoin icon

### PR DESCRIPTION
**Pull request by school-coin**
Transfered cryptonote repo from tgroh007 account over to the new school-coin git account. Changed out SCC-icon.png with schoolcoin-icon.png

### CODE REVIEW

**Comment by school-coin** [comment]
I thought the issue may of been when I transferred repo over to the new account, it automatically added tgroh007 as a collaborator, So I deleted the collaborator, re-added, went through the process of accepting the collaborator invitation, ran checkout master and said the branch is up to date, ran npm run build to make sure tree was clean no issues. Closed pull request reopened request and still having issues.

**Comment by jerme404** [comment]
Updated, thanks!

**Review by school-coin — COMMENTED** [review]
yo, not seeing the change to the new icon?

**Review by school-coin — COMMENTED** [review]
the new icon is named schoolcoin-icon.png the old icon is SCC-icon.png, should I PR again?

**Comment by jerme404** [comment]
Should be updated now, I forgot to push the changes to server

**Comment by school-coin** [comment]
@jerme404 :+1:

**Pull request closed without merging**
