### PR TITLE
Update Streamer cryptodota

### PR DESCRIPTION
**Pull request by jungelist**
"CryptoDota": {
		"game": "DOTA2",
		"game2": "CSGO",
		"links": {
			"website": "https://www.twitch.tv/cryptodota"
		},
"name": "CryptoDota"

### CODE REVIEW

**Comment by Sajo8** [comment]
nope, wrong repo

**Comment by RocksteadyTC** [comment]
What the fuck is this?

**Comment by jerme404** [comment]
oh, this is for sajo's project

**Comment by Sajo8** [comment]
lmao

**Comment by jungelist** [comment]
have Merci guys xD

Am Do., 1. Nov. 2018 um 21:35 Uhr schrieb Sajo8 <notifications@github.com>:

**Pull request closed without merging**
