### PR TITLE
make json readable

### PR DESCRIPTION
**Pull request by Sajo8**

### CODE REVIEW

**Comment by jerme404** [comment]
Bro...   not even close.

**Comment by Sajo8** [comment]
y-yes?

**Comment by jerme404** [comment]
You're editing the wrong file man.  This is the one you need to change.

screen shot 2018-09-08 at 10 12 10 am

**Comment by Sajo8** [comment]
wait, why?

**Comment by jerme404** [comment]
Because that's what the directions say in the readme.

**Comment by jerme404** [comment]
You don't need to change this file, it's generated automatically.

**Pull request closed without merging**
